### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by hughdbrown** [aurimas13/Solutions-To-Problems#3]
https://github.com/aurimas13/Solutions-To-Problems/blob/d621eaa33b943250834ef477e87cdfd0459981ed/LeetCode/Python%20Solutions/Number%20of%20Subsequences%20That%20Satisfy%20the%20Given%20Sum%20Condition/number.py#L24C56-L25

These two tests fail.

```
...     assert s.numSubseq([1,1,2,2,3,3,4,4,5,5], 8) == 147
```
I believe the correct answer is 1011.

```
...     assert s.numSubseq([1,2,3,4,5,6,7,8,9,10], 10) == 15
```
I believe the correct answer is 341.

**Comment by aurimas13** [comment]
Thank you for pointing it. Fixed it.

**Comment by hughdbrown** [comment]
I don't see a code change on master.
